"""
Tier 1: Base Knowledge — Foundational CRC knowledge that ships with Cadence.

These entries cover clinical trial fundamentals that every CRC needs to know.
Read-only. Not site-specific. ~55 entries across 9 categories.
"""

BASE_KNOWLEDGE = [
    # ── Phases (5) ────────────────────────────────────────────────────────
    {
        "id": "base_001",
        "tier": 1,
        "category": "phases",
        "subcategory": "phase_1",
        "content": "Phase 1 trials focus on safety and dosing in 20-80 healthy volunteers or patients. Dropout is typically low (5-10%) but can spike if side effects are unexpected. CRCs should set clear expectations about adverse event reporting frequency at screening.",
        "therapeutic_area": "General",
        "tags": ["phase_1", "safety", "dosing"],
    },
    {
        "id": "base_002",
        "tier": 1,
        "category": "phases",
        "subcategory": "phase_2",
        "content": "Phase 2 trials test efficacy in 100-300 patients with the target condition. Dropout rates average 20-30%. Key risk window is weeks 4-12 when initial side effects peak but efficacy isn't yet apparent. Proactive check-ins during this window are critical.",
        "therapeutic_area": "General",
        "tags": ["phase_2", "efficacy", "dropout_window"],
    },
    {
        "id": "base_003",
        "tier": 1,
        "category": "phases",
        "subcategory": "phase_3",
        "content": "Phase 3 trials are large (300-3000+ patients), multi-site, and often 12-24 months. Dropout rates average 25-35%. The biggest retention challenge is protocol fatigue — patients tire of frequent visits and procedures. Milestone recognition and progress updates help.",
        "therapeutic_area": "General",
        "tags": ["phase_3", "multi_site", "protocol_fatigue"],
    },
    {
        "id": "base_004",
        "tier": 1,
        "category": "phases",
        "subcategory": "phase_4",
        "content": "Phase 4 (post-marketing) studies monitor long-term safety in real-world populations. Patient engagement is lower because the drug is already approved. Dropout can exceed 40%. Keep visits simple and emphasize the patient's contribution to public health.",
        "therapeutic_area": "General",
        "tags": ["phase_4", "post_marketing", "real_world"],
    },
    {
        "id": "base_005",
        "tier": 1,
        "category": "phases",
        "subcategory": "adaptive_designs",
        "content": "Adaptive trial designs allow protocol modifications (dosing, sample size, endpoints) based on interim data. CRCs must be prepared for mid-study changes to visit schedules or procedures. Communicate changes clearly to patients — uncertainty drives dropout.",
        "therapeutic_area": "General",
        "tags": ["adaptive", "protocol_changes", "communication"],
    },

    # ── Dropout Reasons (8) ───────────────────────────────────────────────
    {
        "id": "base_006",
        "tier": 1,
        "category": "dropout_reasons",
        "subcategory": "transportation",
        "content": "Transportation barriers are the #1 modifiable dropout risk factor, affecting 15-25% of trial participants. Patients living >30 miles from site are 2.5x more likely to withdraw. Solutions: ride services, parking vouchers, mileage reimbursement, or telehealth for non-lab visits.",
        "therapeutic_area": "General",
        "tags": ["transportation", "access", "modifiable"],
    },
    {
        "id": "base_007",
        "tier": 1,
        "category": "dropout_reasons",
        "subcategory": "side_effects",
        "content": "Adverse events cause 20-30% of all trial withdrawals. Patients who report side effects early and receive proactive management are 60% less likely to withdraw than those who suffer silently. Ask specifically about common AEs at every contact — don't wait for patients to volunteer.",
        "therapeutic_area": "General",
        "tags": ["adverse_events", "side_effects", "proactive"],
    },
    {
        "id": "base_008",
        "tier": 1,
        "category": "dropout_reasons",
        "subcategory": "schedule_conflicts",
        "content": "Work and family schedule conflicts account for 15-20% of dropout. Offering flexible visit windows (early morning, evening, weekends) reduces schedule-related dropout by 30%. If protocol allows, batch procedures to minimize total site visits.",
        "therapeutic_area": "General",
        "tags": ["scheduling", "flexibility", "work_conflicts"],
    },
    {
        "id": "base_009",
        "tier": 1,
        "category": "dropout_reasons",
        "subcategory": "caregiver_burden",
        "content": "In trials requiring caregiver accompaniment (Alzheimer's, pediatric, geriatric), caregiver burnout is a hidden dropout driver. If the caregiver can't come, the patient can't come. Always collect backup caregiver contacts and check on caregiver well-being.",
        "therapeutic_area": "General",
        "tags": ["caregiver", "burnout", "accompaniment"],
    },
    {
        "id": "base_010",
        "tier": 1,
        "category": "dropout_reasons",
        "subcategory": "financial",
        "content": "Hidden financial costs (copays for non-study procedures, lost wages, childcare during visits) drive 10-15% of dropout. Discuss financial expectations at screening. Many protocols include stipends — make sure patients know about reimbursement processes.",
        "therapeutic_area": "General",
        "tags": ["financial", "costs", "reimbursement"],
    },
    {
        "id": "base_011",
        "tier": 1,
        "category": "dropout_reasons",
        "subcategory": "protocol_fatigue",
        "content": "Protocol fatigue sets in after month 3-4 for most patients. The novelty wears off, and the burden of visits, fasting, diaries, and procedures feels endless. Combat this by showing patients their progress timeline: 'You've completed 60% of visits — here's what's left.'",
        "therapeutic_area": "General",
        "tags": ["fatigue", "burden", "motivation"],
    },
    {
        "id": "base_012",
        "tier": 1,
        "category": "dropout_reasons",
        "subcategory": "loss_of_equipoise",
        "content": "Patients in placebo-controlled trials may suspect they're on placebo (especially if they feel no improvement) and withdraw to seek active treatment. Reinforce the value of the scientific process and remind patients that even placebo groups receive enhanced medical monitoring.",
        "therapeutic_area": "General",
        "tags": ["placebo", "equipoise", "blinding"],
    },
    {
        "id": "base_013",
        "tier": 1,
        "category": "dropout_reasons",
        "subcategory": "language_barriers",
        "content": "Language barriers increase dropout risk by 40% when interpreter services aren't consistently available. Book interpreters proactively for every visit — don't rely on family members. Provide consent forms and study materials in the patient's preferred language.",
        "therapeutic_area": "General",
        "tags": ["language", "interpreter", "health_literacy"],
    },

    # ── Retention Strategies (10) ─────────────────────────────────────────
    {
        "id": "base_014",
        "tier": 1,
        "category": "retention",
        "subcategory": "pre_call",
        "content": "Pre-visit calls 48 hours before scheduled visits reduce no-shows by 30-40%. Confirm the visit, remind about fasting or medication holds, verify transportation, and ask if the patient has any concerns. A 3-minute call can prevent a costly missed visit.",
        "therapeutic_area": "General",
        "tags": ["pre_call", "reminders", "no_show_prevention"],
    },
    {
        "id": "base_015",
        "tier": 1,
        "category": "retention",
        "subcategory": "flexible_scheduling",
        "content": "Offering 3+ visit time slots per week (including one early morning or evening) reduces schedule-conflict dropout by 25-35%. Work with your site to identify protected time blocks that can accommodate working patients.",
        "therapeutic_area": "General",
        "tags": ["scheduling", "flexibility", "access"],
    },
    {
        "id": "base_016",
        "tier": 1,
        "category": "retention",
        "subcategory": "caregiver_coordination",
        "content": "For trials requiring caregiver presence, maintain a 'caregiver card' with primary and backup contacts, their availability, and transportation needs. Schedule regular caregiver check-ins — they are the unsung retention allies.",
        "therapeutic_area": "General",
        "tags": ["caregiver", "coordination", "backup_contacts"],
    },
    {
        "id": "base_017",
        "tier": 1,
        "category": "retention",
        "subcategory": "transport_assistance",
        "content": "Transport assistance programs (ride services, parking vouchers, gas cards) show consistent 20-30% retention improvement in studies with older or low-income populations. Document transportation barriers at enrollment and proactively offer solutions.",
        "therapeutic_area": "General",
        "tags": ["transportation", "rideshare", "access"],
    },
    {
        "id": "base_018",
        "tier": 1,
        "category": "retention",
        "subcategory": "adherence_tools",
        "content": "Medication adherence tools (pill organizers, reminder apps, dosing calendars) improve compliance by 15-25%. Set them up at the enrollment visit — don't wait for non-adherence to become a problem. Check adherence at every visit and troubleshoot barriers.",
        "therapeutic_area": "General",
        "tags": ["adherence", "medication", "tools"],
    },
    {
        "id": "base_019",
        "tier": 1,
        "category": "retention",
        "subcategory": "milestone_recognition",
        "content": "Recognizing patient milestones (halfway point, final labs, study completion) improves engagement. Simple acknowledgments work: 'You've completed your Week 24 visit — you're past the halfway mark!' This combats protocol fatigue by making progress visible.",
        "therapeutic_area": "General",
        "tags": ["milestones", "motivation", "engagement"],
    },
    {
        "id": "base_020",
        "tier": 1,
        "category": "retention",
        "subcategory": "telehealth",
        "content": "Telehealth visits for non-procedure check-ins reduce patient burden by 40% without compromising data quality. If your protocol allows telehealth for certain visits, offer it as a default — especially during winter months or for patients >20 miles away.",
        "therapeutic_area": "General",
        "tags": ["telehealth", "remote", "burden_reduction"],
    },
    {
        "id": "base_021",
        "tier": 1,
        "category": "retention",
        "subcategory": "reengagement_window",
        "content": "After a missed visit, you have a 72-hour re-engagement window before the patient mentally disengages from the trial. Call within 24 hours, text at 48 hours, escalate to PI at 72 hours. After 7 days, retention drops below 40% for that patient.",
        "therapeutic_area": "General",
        "tags": ["missed_visit", "reengagement", "escalation"],
    },
    {
        "id": "base_022",
        "tier": 1,
        "category": "retention",
        "subcategory": "financial_coordination",
        "content": "Connect patients with financial coordinators at screening to address insurance questions, copay assistance, and reimbursement processes. Patients who understand the financial picture upfront are 35% less likely to cite costs as a withdrawal reason.",
        "therapeutic_area": "General",
        "tags": ["financial", "insurance", "coordination"],
    },
    {
        "id": "base_023",
        "tier": 1,
        "category": "retention",
        "subcategory": "cultural_sensitivity",
        "content": "Cultural sensitivity in patient communication improves retention in diverse populations by 20-30%. Learn about your patient population's health beliefs, communication preferences, and family decision-making structures. Don't assume one approach fits all.",
        "therapeutic_area": "General",
        "tags": ["cultural", "diversity", "communication"],
    },

    # ── Visit Types (6) ──────────────────────────────────────────────────
    {
        "id": "base_024",
        "tier": 1,
        "category": "visits",
        "subcategory": "screening",
        "content": "Screening visits are your first and best retention opportunity. Set expectations clearly: visit frequency, procedures, time commitment, and potential side effects. Patients who feel fully informed at screening are 50% more likely to complete the trial.",
        "therapeutic_area": "General",
        "tags": ["screening", "expectations", "informed_consent"],
    },
    {
        "id": "base_025",
        "tier": 1,
        "category": "visits",
        "subcategory": "baseline",
        "content": "Baseline visits establish the patient's pre-treatment data points. They're often the longest and most complex visit. Prepare patients in advance: give them a checklist of what to bring, explain each procedure, and build in buffer time for questions.",
        "therapeutic_area": "General",
        "tags": ["baseline", "preparation", "data_collection"],
    },
    {
        "id": "base_026",
        "tier": 1,
        "category": "visits",
        "subcategory": "follow_up",
        "content": "Follow-up visits are where retention wins or loses. Keep them efficient (respect patient time), review their experience since last visit, address concerns proactively, and always end with a clear next-steps summary including the next visit date.",
        "therapeutic_area": "General",
        "tags": ["follow_up", "efficiency", "engagement"],
    },
    {
        "id": "base_027",
        "tier": 1,
        "category": "visits",
        "subcategory": "end_of_study",
        "content": "End-of-study visits have surprisingly high no-show rates (15-20%) because patients feel 'done' before final procedures. Emphasize the importance of final assessments for both their safety and the science. Consider offering study results as an incentive to complete.",
        "therapeutic_area": "General",
        "tags": ["end_of_study", "completion", "final_visit"],
    },
    {
        "id": "base_028",
        "tier": 1,
        "category": "visits",
        "subcategory": "unscheduled",
        "content": "Unscheduled visits (AE follow-up, protocol deviations, early termination) require careful documentation. Use them as retention touchpoints — address the patient's concerns, assess ongoing willingness to participate, and document everything in real-time.",
        "therapeutic_area": "General",
        "tags": ["unscheduled", "adverse_events", "documentation"],
    },
    {
        "id": "base_029",
        "tier": 1,
        "category": "visits",
        "subcategory": "fasting",
        "content": "Fasting visits have 2x the no-show rate of regular visits. Schedule them as early morning appointments, send explicit fasting instructions 48 hours before (water OK, medications per protocol), and confirm compliance on arrival before drawing labs.",
        "therapeutic_area": "General",
        "tags": ["fasting", "labs", "no_show_risk"],
    },

    # ── Regulatory (6) ───────────────────────────────────────────────────
    {
        "id": "base_030",
        "tier": 1,
        "category": "regulatory",
        "subcategory": "informed_consent",
        "content": "Informed consent is a process, not a signature. Re-consent is required when the protocol changes materially (new risks, new procedures, amended visit schedule). Document the consent discussion, not just the signature. Use teach-back to verify understanding.",
        "therapeutic_area": "General",
        "tags": ["consent", "icf", "reconsent"],
    },
    {
        "id": "base_031",
        "tier": 1,
        "category": "regulatory",
        "subcategory": "protocol_deviations",
        "content": "Protocol deviations must be documented within 24 hours and reported to the IRB per institutional timelines (typically 5-10 business days for minor, 24-48 hours for major). Common deviations: missed visit windows, wrong lab timing, consent issues. Prevention > reporting.",
        "therapeutic_area": "General",
        "tags": ["deviations", "irb", "reporting"],
    },
    {
        "id": "base_032",
        "tier": 1,
        "category": "regulatory",
        "subcategory": "ae_reporting",
        "content": "Adverse events must be graded (CTCAE scale 1-5), assessed for relatedness, and reported per protocol timelines. SAEs (Serious Adverse Events) require reporting within 24 hours to sponsor and IRB. Always err on the side of over-reporting — unreported AEs are audit findings.",
        "therapeutic_area": "General",
        "tags": ["adverse_events", "sae", "ctcae", "reporting"],
    },
    {
        "id": "base_033",
        "tier": 1,
        "category": "regulatory",
        "subcategory": "irb_amendments",
        "content": "IRB amendments are required before implementing any protocol change. Timelines vary: administrative changes (2-4 weeks), minor amendments (4-6 weeks), major amendments (6-12 weeks). Plan ahead — don't let pending amendments delay patient care.",
        "therapeutic_area": "General",
        "tags": ["irb", "amendments", "timelines"],
    },
    {
        "id": "base_034",
        "tier": 1,
        "category": "regulatory",
        "subcategory": "audit_readiness",
        "content": "Audit readiness = ongoing documentation discipline. Key areas: consent forms current and complete, source documents match EDC entries, AE reporting timely, drug accountability accurate, and visit windows documented. Don't prepare for audits — maintain audit-ready records daily.",
        "therapeutic_area": "General",
        "tags": ["audit", "documentation", "compliance"],
    },
    {
        "id": "base_035",
        "tier": 1,
        "category": "regulatory",
        "subcategory": "source_documentation",
        "content": "Source documents are the original records of clinical data. They must be contemporaneous (recorded at time of observation), accurate, legible, and attributable. Electronic source is increasingly accepted but requires validation. Never backfill source documents.",
        "therapeutic_area": "General",
        "tags": ["source_docs", "records", "data_integrity"],
    },

    # ── Therapeutic Areas (8) ────────────────────────────────────────────
    {
        "id": "base_036",
        "tier": 1,
        "category": "therapeutic_areas",
        "subcategory": "nash",
        "content": "NASH trials have unique challenges: liver biopsies cause anxiety and dropout (20-30% at biopsy visits), fasting visits are frequent, and patients may feel asymptomatic. Educate patients that NASH is a progressive disease even without symptoms. Pre-biopsy counseling reduces dropout by 15%.",
        "therapeutic_area": "NASH",
        "tags": ["nash", "liver_biopsy", "fasting", "asymptomatic"],
    },
    {
        "id": "base_037",
        "tier": 1,
        "category": "therapeutic_areas",
        "subcategory": "alzheimers",
        "content": "Alzheimer's trials require study partner/caregiver involvement at every visit. Cognitive decline during the trial can affect consent capacity — have a plan for ongoing consent assessment. Screen failures are high (40-50%) due to amyloid confirmation requirements.",
        "therapeutic_area": "Alzheimer's",
        "tags": ["alzheimers", "caregiver", "consent_capacity", "amyloid"],
    },
    {
        "id": "base_038",
        "tier": 1,
        "category": "therapeutic_areas",
        "subcategory": "cardiovascular",
        "content": "Cardiovascular trials often have elderly patients with multiple comorbidities and polypharmacy. Medication reconciliation at every visit is critical. Cardiac imaging visits (MRI, echo) are time-intensive — schedule with buffer and coordinate with imaging center availability.",
        "therapeutic_area": "Heart Failure",
        "tags": ["cardiovascular", "polypharmacy", "imaging", "elderly"],
    },
    {
        "id": "base_039",
        "tier": 1,
        "category": "therapeutic_areas",
        "subcategory": "glp1",
        "content": "GLP-1 trials see highest dropout between weeks 4-8 due to GI side effects (nausea, vomiting, diarrhea). Proactive nausea management education at enrollment cuts early dropout by 25%. Titration schedules must be followed carefully — too fast = more GI issues.",
        "therapeutic_area": "GLP-1",
        "tags": ["glp1", "gi_side_effects", "nausea", "titration"],
    },
    {
        "id": "base_040",
        "tier": 1,
        "category": "therapeutic_areas",
        "subcategory": "oncology",
        "content": "Oncology trials have unique retention dynamics: patients are highly motivated (treatment access) but physically depleted by treatment. Flexible scheduling around chemo cycles, nausea management, and emotional support are key. Dropout often correlates with disease progression rather than dissatisfaction.",
        "therapeutic_area": "Oncology",
        "tags": ["oncology", "chemo_cycles", "disease_progression"],
    },
    {
        "id": "base_041",
        "tier": 1,
        "category": "therapeutic_areas",
        "subcategory": "rare_disease",
        "content": "Rare disease trials have small populations (often <100 globally), so every patient is critical. Patients travel far and are highly engaged communities. Leverage patient advocacy groups for recruitment. Retention is usually high (>80%) because patients have few treatment alternatives.",
        "therapeutic_area": "Rare Disease",
        "tags": ["rare_disease", "small_population", "advocacy"],
    },
    {
        "id": "base_042",
        "tier": 1,
        "category": "therapeutic_areas",
        "subcategory": "pediatric",
        "content": "Pediatric trials require assent (child) plus consent (parent/guardian). School schedules constrain visit timing — summer and school breaks are ideal for intensive visit windows. Both parent and child may experience trial fatigue; engage both in retention strategies.",
        "therapeutic_area": "Pediatric",
        "tags": ["pediatric", "assent", "school_schedule", "family"],
    },
    {
        "id": "base_043",
        "tier": 1,
        "category": "therapeutic_areas",
        "subcategory": "mental_health",
        "content": "Mental health trials face stigma-related dropout and fluctuating patient engagement due to disease nature. Build strong therapeutic alliance, offer remote visit options, and have a clear crisis protocol. Missed visits may signal clinical worsening, not disinterest — follow up with care.",
        "therapeutic_area": "Mental Health",
        "tags": ["mental_health", "stigma", "therapeutic_alliance", "crisis"],
    },

    # ── CRC Workflow (6) ─────────────────────────────────────────────────
    {
        "id": "base_044",
        "tier": 1,
        "category": "crc_workflow",
        "subcategory": "daily_prioritization",
        "content": "Start each day with: (1) Check for overdue visits/tasks, (2) Review today's scheduled visits and prep, (3) Follow up on yesterday's missed contacts, (4) Review pending queries, (5) Check upcoming visit week for pre-calls. Prioritize by risk level — high-risk patients first.",
        "therapeutic_area": "General",
        "tags": ["daily_routine", "prioritization", "workflow"],
    },
    {
        "id": "base_045",
        "tier": 1,
        "category": "crc_workflow",
        "subcategory": "missed_visit_escalation",
        "content": "Missed visit escalation ladder: Day 1 — phone call (2 attempts). Day 2 — SMS/text. Day 3 — email with rescheduling link. Day 5 — PI notification. Day 7 — formal protocol deviation if outside visit window. Document every attempt with date, time, and outcome.",
        "therapeutic_area": "General",
        "tags": ["missed_visit", "escalation", "documentation"],
    },
    {
        "id": "base_046",
        "tier": 1,
        "category": "crc_workflow",
        "subcategory": "query_resolution",
        "content": "Data queries should be resolved within 5 business days (industry standard). Track query aging daily. Common resolution blockers: waiting on PI signature, missing source documents, discrepancies between paper and electronic records. Escalate queries >10 days old to site PI.",
        "therapeutic_area": "General",
        "tags": ["queries", "data_management", "resolution"],
    },
    {
        "id": "base_047",
        "tier": 1,
        "category": "crc_workflow",
        "subcategory": "handoff_protocols",
        "content": "When handing off patients to another CRC (vacation, turnover, reassignment), provide: current status of each patient, pending tasks with deadlines, any patient-specific preferences or concerns, and key contact information. A poor handoff loses patients.",
        "therapeutic_area": "General",
        "tags": ["handoff", "transition", "documentation"],
    },
    {
        "id": "base_048",
        "tier": 1,
        "category": "crc_workflow",
        "subcategory": "site_initiation",
        "content": "Site initiation visits (SIVs) set the tone for the entire trial. Prepare by: reading the full protocol, setting up regulatory binders, configuring EDC access, training all site staff, and establishing a visit scheduling system. First impressions with sponsors matter.",
        "therapeutic_area": "General",
        "tags": ["siv", "initiation", "preparation"],
    },
    {
        "id": "base_049",
        "tier": 1,
        "category": "crc_workflow",
        "subcategory": "closeout",
        "content": "Study closeout requires: all queries resolved, drug accountability reconciled, final monitoring visit completed, regulatory documents archived, and end-of-study reports filed. Start closeout preparation 30 days before the last patient's last visit.",
        "therapeutic_area": "General",
        "tags": ["closeout", "archiving", "final_visit"],
    },

    # ── Adverse Events (3) ───────────────────────────────────────────────
    {
        "id": "base_050",
        "tier": 1,
        "category": "adverse_events",
        "subcategory": "grading",
        "content": "CTCAE grading: Grade 1 (mild, no intervention needed), Grade 2 (moderate, minimal intervention), Grade 3 (severe, hospitalization or significant intervention), Grade 4 (life-threatening), Grade 5 (death). Always grade at the time of maximum intensity.",
        "therapeutic_area": "General",
        "tags": ["ctcae", "grading", "severity"],
    },
    {
        "id": "base_051",
        "tier": 1,
        "category": "adverse_events",
        "subcategory": "reporting_timelines",
        "content": "AE reporting timelines: Non-serious AEs — document at next scheduled assessment. SAEs — report to sponsor within 24 hours of awareness, IRB per institutional policy (usually 24-48 hours for unexpected, 5-10 days for expected). SUSARs go to regulatory authorities within 7-15 days.",
        "therapeutic_area": "General",
        "tags": ["reporting", "sae", "susar", "timelines"],
    },
    {
        "id": "base_052",
        "tier": 1,
        "category": "adverse_events",
        "subcategory": "sae_vs_ae",
        "content": "An AE becomes an SAE if it results in: death, life-threatening condition, hospitalization (or prolongation), persistent disability, congenital anomaly, or other medically important event. When in doubt, report as SAE — under-reporting is a far greater risk than over-reporting.",
        "therapeutic_area": "General",
        "tags": ["sae", "classification", "safety"],
    },

    # ── Data Management (3) ──────────────────────────────────────────────
    {
        "id": "base_053",
        "tier": 1,
        "category": "data_management",
        "subcategory": "edc_entry",
        "content": "EDC (Electronic Data Capture) entry should happen within 24-48 hours of the patient visit. Same-day entry is gold standard. Backlog of data entry creates query cascades and monitoring findings. Build EDC entry into your visit workflow, not as an afterthought.",
        "therapeutic_area": "General",
        "tags": ["edc", "data_entry", "timeliness"],
    },
    {
        "id": "base_054",
        "tier": 1,
        "category": "data_management",
        "subcategory": "query_lifecycle",
        "content": "Query lifecycle: Opened (by monitor or automated checks) → Assigned (to CRC) → In Progress (investigation) → Responded (CRC submits fix) → Closed (monitor accepts). Keep queries <5 days old. Queries >30 days old flag the site as 'high risk' in sponsor dashboards.",
        "therapeutic_area": "General",
        "tags": ["queries", "lifecycle", "data_quality"],
    },
    {
        "id": "base_055",
        "tier": 1,
        "category": "data_management",
        "subcategory": "source_requirements",
        "content": "Source document requirements: ALCOA+ (Attributable, Legible, Contemporaneous, Original, Accurate + Complete, Consistent, Enduring, Available). Every data point in EDC must trace back to a source document. Missing source = audit finding. Maintain a source document worksheet.",
        "therapeutic_area": "General",
        "tags": ["alcoa", "source_docs", "traceability"],
    },
]


class BaseKnowledge:
    """Tier 1: Foundational CRC knowledge. Read-only, ships with Cadence."""

    def __init__(self):
        self.entries = list(BASE_KNOWLEDGE)

    def get_entries(self, category=None):
        if category:
            return [e for e in self.entries if e["category"] == category]
        return list(self.entries)

    def get_categories(self):
        return sorted(set(e["category"] for e in self.entries))

    def search(self, query):
        """Simple keyword search across content and tags."""
        words = query.lower().split()
        results = []
        for entry in self.entries:
            text = f"{entry['content']} {' '.join(entry['tags'])} {entry['category']} {entry.get('subcategory', '')} {entry.get('therapeutic_area', '')}".lower()
            matches = sum(1 for w in words if w in text)
            if matches > 0:
                results.append({**entry, "_score": matches / len(words)})
        return sorted(results, key=lambda x: x["_score"], reverse=True)
